services:
  - type: web
    name: redis-snowflake-demo
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: REDIS_URL
        sync: false
      - key: SNOWFLAKE_ACCOUNT
        sync: false
      - key: SNOWFLAKE_USERNAME
        sync: false
      - key: SNOWFLAKE_PASSWORD
        sync: false
      - key: SNOWFLAKE_WAREHOUSE
        sync: false
      - key: SNOWFLAKE_DATABASE
        sync: false
      - key: SNOWFLAKE_SCHEMA
        sync: false
